#include "motor.h"

void FullSpeedForward()
{
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,10000);
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,10000);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_2);
	HAL_GPIO_WritePin(LeftIn1GPIO, LeftIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LeftIn2GPIO, LeftIn2Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RightIn1GPIO, RightIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RightIn2GPIO, RightIn2Pin, GPIO_PIN_RESET);
}

void FullSpeedBack()
{
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,10000);
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,10000);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_2);
	HAL_GPIO_WritePin(LeftIn1GPIO, LeftIn1Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LeftIn2GPIO, LeftIn2Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RightIn1GPIO, RightIn1Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RightIn2GPIO, RightIn2Pin, GPIO_PIN_SET);
}

void TurnLeft()
{
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,10000);
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,10000);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_2);
	HAL_GPIO_WritePin(LeftIn1GPIO, LeftIn1Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LeftIn2GPIO, LeftIn2Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RightIn1GPIO, RightIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RightIn2GPIO, RightIn2Pin, GPIO_PIN_RESET);
}

void TurnRight()
{
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,10000);
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,10000);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_2);
	HAL_GPIO_WritePin(LeftIn1GPIO, LeftIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LeftIn2GPIO, LeftIn2Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RightIn1GPIO, RightIn1Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RightIn2GPIO, RightIn2Pin, GPIO_PIN_SET);
}
void SuspendedTurnLeft()
{
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,10000);
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,10000);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_2);
	HAL_GPIO_WritePin(LeftIn1GPIO, LeftIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LeftIn2GPIO, LeftIn2Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RightIn1GPIO, RightIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RightIn2GPIO, RightIn2Pin, GPIO_PIN_RESET);
}

void SuspendedTurnRight()
{
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,10000);
	__HAL_TIM_SET_COMPARE(&htim3,TIM_CHANNEL_2,10000);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_2);
	HAL_GPIO_WritePin(LeftIn1GPIO, LeftIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LeftIn2GPIO, LeftIn2Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RightIn1GPIO, RightIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RightIn2GPIO, RightIn2Pin, GPIO_PIN_SET);
}
void BrakeTurnLeft()
{
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,10000);
	__HAL_TIM_SET_COMPARE(&htim3,TIM_CHANNEL_2,10000);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_2);
	HAL_GPIO_WritePin(LeftIn1GPIO, LeftIn1Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LeftIn2GPIO, LeftIn2Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RightIn1GPIO, RightIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RightIn2GPIO, RightIn2Pin, GPIO_PIN_RESET);
}
void BrakeTurnRight()
{
	__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,10000);
	__HAL_TIM_SET_COMPARE(&htim3,TIM_CHANNEL_2,10000);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_1);
	HAL_TIM_PWM_Start(&htim2,TIM_CHANNEL_2);
	HAL_GPIO_WritePin(LeftIn1GPIO, LeftIn1Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LeftIn2GPIO, LeftIn2Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RightIn1GPIO, RightIn1Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RightIn2GPIO, RightIn2Pin, GPIO_PIN_RESET);
}