#include "motor.h"

void FullSpeedForward()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_RESET);
}

void FullSpeedBack()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_SET);
}

void TurnLeft()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_RESET);
}

void TurnRight()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_SET);
}
void SuspendedTurnLeft()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_RESET);
}

void SuspendedTurnRight()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_SET);
}
void BrakeTurnLeft()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_RESET);
}
void BrakeTurnRight()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_RESET);
}

void Stop()
{
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,499);
	//__HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_2,499);
	HAL_GPIO_WritePin(LEFT_IN1_GPIO_Port, LEFT_IN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LEFT_IN2_GPIO_Port, LEFT_IN2_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN1_GPIO_Port, RIGHT_IN1_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(RIGHT_IN2_GPIO_Port, RIGHT_IN2_Pin, GPIO_PIN_RESET);
}